MODEL_CFG:
  PRETRAINED: '' # '/home/guest/speaking_fridgey/ocr_exp_v2/weight/layer5_HENNET_Hangul_Converter_RGB_FINANCE_CROPED_SENTNECE_TARGETNUM_3e_4/2023-02-16_min_loss.pth' # '/home/guest/speaking_fridgey/ocr_exp_v2/weight/layer5_HENNET_Hangul_Converter_RGB_Package_/2023-02-11_min_loss.pth' # '/home/guest/ocr_exp_v2/weight/layer5_relu_MULTI_NORM_0to1_ADAM_STEP/2023-01-31_min_loss.pth'
  USE_RES: !!bool true # true # false
  SEPERABLE_FFN: !!bool true # true # false # true #  false ## Transformer Encoder의 FFN을 Convolution을 사용할지 말지
  PRETRAINED_OPTIM: ''
  MAKE_OBJECT_QUERY: !!bool true
  ADAPTIVE_PE: !!bool false  # true
  TPS: !!bool false # true
  BATCH_SIZE: !!int 300 # 300
  RES_IN: 32
  MAX_SEQ_LENGTH: 75 #  45 # 30 #75
  ENCODER_LAYER_NUM: !!int 5 # 6 # 5 # 6 # 5 # 12
  EMBEDDING_DIM: 512
  ATTENTIONAL_TRANSFORMER: !!bool false # true # false
  FEED_FORWARD_DIM: 2048
  HEAD_NUM: !!int 8
  IMG_W: 192 # 128 # 192 # 128 # 192
  IMG_H: 32 # 128
  USE_CONV: !!bool false #  true
  ACTIVATION: !!str 'RELU' # 'TANH' # 'LEAKYRELU' # 'GELU' # 'TANH' 
  RGB: !!bool true # false

TRAIN_CFG:
  LOSS_FN: "CE" # "FOCAL" # 'SOFTCE'
  LOSS_WEIGHT: !!bool false # true
  NUM_WEIGHT: !!float 2.0
  ENG_WEIGHT: !!float 2.0
  OPTIMIZER: 'ADAM' # 'SGD' # 'ADAM'
  SCHEDULER: 'STEP' # 'COSINE' # 'CYCLIC' # 
  MOMENTUM: 0.9
  LR: !!float 2e-4 # 1e-4 # 1e-4 ## 3e-4 ## => 신기하게 ADAM은 1e-4 ~ 1e-5를 시작으로 잡는 것이, SGD는 0.1 ~ 0.01 정도를 시작 learning rate로 잡는 것이 효과적이다.
  DEBUG: !!bool false
  BATCH_SIZE: 300
  EPOCH: !!int 100
  EVAL_EPOCH: !!int 10
  WEIGHT_FOLDER: '/home/guest/speaking_fridgey/ocr_exp_v2/weight'
  OPTIM_FOLDER: '/home/guest/speaking_fridgey/ocr_exp_v2/optim'

DATA_CFG:
  RGB: !!bool true 
  USE_BANK: !!bool false  # => 금
  USE_COSMETICS: !!bool true 
  USE_MEDICINE: !!bool true
  IMG_H: !!int 32
  IMG_W: !!int 192 # 128 
  MAX_LENGTH: !!int 75
  CONVERTER: !!str "hangul" # "general" 
  TARGET_NUM: !!bool true  # false 
  TARGET_ENG: !!bool false #  true 솔직히 영어 부분은 그렇게 중요하다곤 생각이 안들기 때문에 적어도 숫자만큼은 완벽하게 인식할 수 있게하자
  TARGET_BOTH: !!bool false
  ## ADD_*얘네는 Label Converter 정의하는데 필요함
  ADD_NUM: !!bool true # false 
  ADD_ENG: !!bool true # false 
  RATIO: 
    - 1.0 ## Croped Sentence Dataset Ratio
    - 0.1 ## Package Dataset Ratio
  DATASET: 
    - 'HENDatasetV2'
    - 'HENDatasetV3'
  USE_OUTDOOR: !!bool false
  BASE_FOLDER: '/home/guest/speaking_fridgey/ocr_exp_v2/data/printed_text' ## 학습을 text_recognition 폴더 내에서 시킬 것이기 때문에 
  ### MEAN, STD는 0.5로 고정으로 가는게 나을 것 같다
  GRAY_MEAN: 0.0 # 0.8 # 0.0 #  0.5
  GRAY_STD: 1.0 # 0.37 # 1.0 # 0.5 
  MEAN:  [0.5,0.5,0.5] # [0.8,0.8,0.8] #  [0.0,0.0,0.0] #[0.5,0.5,0.5] 
  STD:  [0.5,0.5,0.5] # [0.37,0.37,0.37] # [1.0,1.0,1.0] # [0.5,0.5,0.5] #
  BASE_CHARACTERS: 
    - ' ' ## 공백은 종성에 무조건 있기 때문에 꼭 포함을 시켜야 한다.
    - 'ㄱ'
    - 'ㄲ'
    - 'ㄳ'
    - 'ㄴ'
    - 'ㄵ'
    - 'ㄶ'
    - 'ㄷ'
    - 'ㄸ'
    - 'ㄹ'
    - 'ㄺ'
    - 'ㄻ'
    - 'ㄼ'
    - 'ㄽ'
    - 'ㄾ'
    - 'ㄿ'
    - 'ㅀ'
    - 'ㅁ'
    - 'ㅂ'
    - 'ㅃ'
    - 'ㅄ'
    - 'ㅅ'
    - 'ㅆ'
    - 'ㅇ'
    - 'ㅈ'
    - 'ㅉ'
    - 'ㅊ'
    - 'ㅋ'
    - 'ㅌ'
    - 'ㅍ'
    - 'ㅎ'
    - 'ㅏ'
    - 'ㅐ'
    - 'ㅑ'
    - 'ㅒ'
    - 'ㅓ'
    - 'ㅔ'
    - 'ㅕ'
    - 'ㅖ'
    - 'ㅗ'
    - 'ㅘ'
    - 'ㅙ'
    - 'ㅚ'
    - 'ㅛ'
    - 'ㅜ'
    - 'ㅝ'
    - 'ㅞ'
    - 'ㅟ'
    - 'ㅠ'
    - 'ㅡ'
    - 'ㅢ'
    - 'ㅣ'

  ADD_SPECIAL: !!bool False

